version: "3"

services:
  client:
    image: nginx
    container_name: ${PROJ_NAME}
    restart: always
    ports: [80]
    labels:
      - traefik.http.routers.${PROJ_NAME}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${PROJ_NAME}.entrypoints=web
    volumes:
      - ./shared:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    name: traefik
    external: true